import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const geistPoppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "900"],
  variable: "--font-poppins",
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "NextJs Optimization",
  description: "Generated by NextJs Optimization",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistPoppins.variable}  prose prose-blue md:prose-xl dark:prose-invert`}
      >
        {children}
      </body>
    </html>
  );
}
